server:
  port: 9526

spring:
  ########### mysql
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/mybatis_plus?serverTimezone=GMT%2B8
    username: root
    password: root
    hikari:
      maximum-pool-size: 10  # 最大连接池数
      max-lifetime: 1770000
    ################ redis
  redis:
    host: 127.0.0.1
    port: 6379
    database: 5
    timeout: 5000
    jedis:
      pool:
        # 连接池中的最大空闲连接，默认值也是8。
        max-idle: 500
        # 连接池中的最小空闲连接，默认值也是0。
        min-idle: 50
        # 如果赋值为-1，则表示不限制；如果pool已经分配了maxActive个jedis实例，则此时pool的状态为exhausted(耗尽)
        max-active: 1000
        # 等待可用连接的最大时间，单位毫秒，默认值为-1，表示永不超时。如果超过等待时间，则直接抛出JedisConnectionException
        max-wait: 2000

# mp
mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    map-underscore-to-camel-case: true
  global-config:
    db-config:
      logic-not-delete-value: 0
      logic-delete-value: 1
      logic-delete-field: deleted
  mapper-locations: classpath:/mapper/*.xml

# 自定义starter 配置
com:
  fhw:
    name: fhw
    version: 1.0.0

# 日志部分
logging:
  config: classpath:logback.xml
  level:
    com.fhw.guliclassroom.common.practice.controller: trace
